[project]
name = "nodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pyqt6",
    "pyyaml>=6.0",
    "qtpy>=2.4.3",
    "ruff>=0.15.1",
]

[tool.ruff]
line-length = 80
